from automation.config import config

CONFIG_YAML_FILE = config("CONFIG_YAML_FILE")
REQUIREMENTS_YAML_FILE = config("REQUIREMENTS_YAML_FILE")
USER_INPUT_ENV = config("USER_INPUT_ENV")
ROUTE_NOTIFICATION = config("ROUTE_NOTIFICATION")
RECIEVER_NOTIFICATION = config("RECIEVER_NOTIFICATION")
TEMPLATES_DIRECTORY = config("TEMPLATES_DIRECTORY")
PROMETHEUS_CONFIG = config("PROMETHEUS_CONFIG")
EA_RULES = config("EA_RULES")
